-- AlterTable
ALTER TABLE `customer` MODIFY `Full_Name` VARCHAR(191) NULL,
    MODIFY `Passport_No` VARCHAR(191) NULL,
    MODIFY `CNIC_No` VARCHAR(191) NULL,
    MODIFY `Father_Name` VARCHAR(191) NULL,
    MODIFY `Nationality` VARCHAR(191) NULL,
    MODIFY `City` VARCHAR(191) NULL,
    MODIFY `Address` VARCHAR(191) NULL,
    MODIFY `Phone_No1` VARCHAR(191) NULL,
    MODIFY `Gender` VARCHAR(191) NULL,
    MODIFY `Age` VARCHAR(191) NULL;
